#include "res.h"

// ---------------------------------------------------------------------------
const char *empty_img =
    "PHN2ZyBoZWlnaHQ9JzEwMHB4JyB3aWR0aD0nMTAwcHgnICBmaWxsPSIjZmZmZmZmIiB4bWxucz"
    "0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIGRhdGEtbmFtZT0iTGF5ZXIgMSIgdmlld0Jv"
    "eD0iMCAwIDI0IDI0IiB4PSIwcHgiIHk9IjBweCI+"
    "PHRpdGxlPnN2Zyw8L3RpdGxlPjxwYXRoIGQ9Ik0yMS41LDEzLjUyN2EuNi42LDAsMCwxLS40Mj"
    "QuNzM1bC0yLjcwNy43MjVMMjAuOTYsMTYuNDhhLjYuNiwwLDEsMS0uNiwxLjAzOWwtMi41ODYt"
    "MS40OTMuNzI1LDIuNzA4YS42LjYsMCwwLDEtLjQyNC43MzUuNjExLjYxMSwwLDAsMS0uMTU1Lj"
    "AyMS42LjYsMCwwLDEtLjU3OS0uNDQ1bC0xLjAzNS0zLjg2NkwxMi42LDEzLjAzOXY0LjI3OGwy"
    "LjgzLDIuODNhLjYuNiwwLDEsMS0uODQ4Ljg0OUwxMi42LDE5LjAxNFYyMmEuNi42LDAsMSwxLT"
    "EuMiwwVjE5LjAxNEw5LjQxOCwyMWEuNi42LDAsMSwxLS44NDgtLjg0OWwyLjgzLTIuODNWMTMu"
    "MDM5bC0zLjcwNiwyLjE0TDYuNjU5LDE5LjA0NGEuNi42LDAsMCwxLS41NzkuNDQ1LjYxMS42MT"
    "EsMCwwLDEtLjE1NS0uMDIxLjYuNiwwLDAsMS0uNDI0LS43MzVsLjcyNS0yLjcwOEwzLjY0LDE3"
    "LjUyYS42LjYsMCwxLDEtLjYtMS4wMzlsMi41ODYtMS40OTMtMi43MDctLjcyNUEuNi42LDAsMC"
    "wxLDMuMjI5LDEzLjFMNy4xLDE0LjEzOSwxMC44LDEyLDcuMSw5Ljg2MSwzLjIyOSwxMC45YS42"
    "MTEuNjExLDAsMCwxLS4xNTUuMDIxLjYuNiwwLDAsMS0uMTU1LTEuMThsMi43MDctLjcyNUwzLj"
    "A0LDcuNTJhLjYuNiwwLDAsMSwuNi0xLjAzOUw2LjIyNiw3Ljk3NCw1LjUsNS4yNjZhLjYuNiww"
    "LDEsMSwxLjE1OC0uMzExTDcuNjk0LDguODIxbDMuNzA2LDIuMTRWNi42ODNMOC41NywzLjg1M0"
    "EuNi42LDAsMCwxLDkuNDE4LDNMMTEuNCw0Ljk4NlYyYS42LjYsMCwxLDEsMS4yLDBWNC45ODZM"
    "MTQuNTgyLDNhLjYuNiwwLDAsMSwuODQ4Ljg0OUwxMi42LDYuNjgzdjQuMjc4bDMuNzA2LTIuMT"
    "QsMS4wMzUtMy44NjZhLjYuNiwwLDEsMSwxLjE1OC4zMTFsLS43MjUsMi43MDhMMjAuMzYsNi40"
    "OGEuNi42LDAsMCwxLC42LDEuMDM5TDE4LjM3NCw5LjAxM2wyLjcwNy43MjVhLjYuNiwwLDAsMS"
    "0uMTU1LDEuMTguNjExLjYxMSwwLDAsMS0uMTU1LS4wMjFMMTYuOSw5Ljg2MSwxMy4yLDEybDMu"
    "NywyLjEzOUwyMC43NzEsMTMuMUEuNi42LDAsMCwxLDIxLjUsMTMuNTI3WiI+"
    "PC9wYXRoPjwvc3ZnPg==";

// ---------------------------------------------------------------------------
#include "res_gen.c"
